// This file has been autogenerated from a class added in the UI designer.

using System;
using App1.iOS.Data;
using App1.iOS.DataSources;
using UIKit;

namespace App1.iOS
{
	public partial class CollectionTest : UIViewController
	{
		private UICollectionViewDataSource dataSource;

		public CollectionTest(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			var mapper = new CustomerDataSourceMapper();
			var customerDataSource = new CustomerViewSource(CollectionView, mapper);
			CollectionView.RegisterNibForCell(ColCell.Nib, ColCell.Key);

			CollectionView.DataSource = customerDataSource;
			CollectionView.CollectionViewLayout = new TestViewLayout();

			// bindings
			customerDataSource.ItemsSource = Customer.GetCustomerList(100);
			dataSource = customerDataSource;
		}
	}
}
