// This file has been autogenerated from a class added in the UI designer.

using System;
using App1.iOS.Data;
using CoreGraphics;
using Foundation;
using UIKit;

namespace App1.iOS
{
	public partial class SyncfusionTest : UIViewController
	{
		public SyncfusionTest(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			FlexGridView.ItemsSource = Customer.GetCustomerList(100);
		}
		public override void ViewDidLayoutSubviews()
		{
			base.ViewDidLayoutSubviews();
			FlexGridView.Frame = new CGRect(this.View.Frame.X, this.View.Frame.Y,
				this.View.Frame.Width, this.View.Frame.Height);

		}
	}
}
