// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace App1.iOS
{
	public partial class TestViewCell : UICollectionViewCell
	{
		public TestViewCell(IntPtr handle) : base(handle)
		{
		}
	}
}
